#!/bin/bash
#
# App     This shell script takes care of starting and stopping App
#
# chkconfig: - 80 20
#
### BEGIN INIT INFO
# Provides: lcs
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Short-Description: start and stop tomcat
### END INIT INFO

APP_USER=app
APP_HOME="/home/aaa/app"
SHUTDOWN_WAIT=45
PROCESS_NAME=app
START_SHELL=runApp.sh
STOP_SHELL=stopApp.sh

app_pid() {
    echo `ps aux | grep -w $PROCESS_NAME | grep -v grep | awk '{ print $2 }'`
}

start() {
    pid=$(app_pid)
    if [ -n "$pid" ]
    then
        echo "$PROCESS_NAME is already running (pid: $pid)"
    else
        # Start lcs
        echo "Starting $PROCESS_NAME"
        /bin/su - -c "cd $APP_HOME/bin && $APP_HOME/bin/$START_SHELL" $APP_USER
    fi
    return 0
}

stop() {
    pid=$(app_pid)
    if [ -n "$pid" ]
    then
        echo "Stoping $PROCESS_NAME"
        /bin/su - -c "cd $APP_HOME/bin && $APP_HOME/bin/$STOP_SHELL" $APP_USER

    let kwait=$SHUTDOWN_WAIT
    count=0
    count_by=5
    until [ `ps -p $pid | grep -c $pid` = '0' ] || [ $count -gt $kwait ]
    do
        echo "Waiting for processes to exit. Timeout before we kill the pid: ${count}/${kwait}"
        sleep $count_by
        let count=$count+$count_by;
    done

    if [ $count -gt $kwait ]; then
        echo "Killing processes which didn't stop after $SHUTDOWN_WAIT seconds"
        kill -9 $pid
    fi
    else
        echo "$PROCESS_NAME is not running"
    fi

    return 0
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        pid=$(app_pid)
        if [ -n "$pid" ]
        then
           echo "$PROCESS_NAME is running with pid: $pid"
        else
           echo "$PROCESS_NAME is not running"
        fi
        ;;
esac

exit 0
